### ISSUE TITLE
Syscall convention for darwin

### ISSUE THREAD

**Issue by michael105** [streamich/libsys#123]
Are you sure about the return register of the syscalls at darwin x64?
(https://github.com/streamich/libsys/blob/master/syscall/darwin.c)
According to the Abi specification, the return value is in eax. 
(Not r11, but r11 is clobbered) 

But I already needed to learn, there are other registers involved at user level than at kernel level.
So I'm asking, cause I'm looking for information.

**Comment by michael105** [comment]
.. here is a link to the abi.
https://github.com/hjl-tools/x86-psABI/wiki/X86-psABI

**Comment by streamich** [comment]
In line

```c
: "=a" (result), "=r" (flags)
```

I believe `=a` means EAX register, so result comes from EAX. What `"movq %%r11, %1;\n"` does and why it is there I cannot recall now.

**Comment by michael105** [comment]
Thanks for your clarification, I completely overlooked .. well.
I confused param 1 with param 2, %0 and %1 in assembly.
the movq copies the flags to (flags). 

Thanks for your good work, btw.
